### ISSUE TITLE
Implementation Bug?

### ISSUE THREAD

**Issue by bicsi** [bombela/sparseset#1]
It seems that the library has an implementation bug. When removing the last element in the dense array, an array out of bounds error is triggered. I think the line below is the issue:

https://github.com/bombela/sparseset/blob/5a117722b044e1d70c759c5ee9018e11dcefa4df/src/lib.rs#L178

I think the correct condition in the `if` statement should be:
`if dense_idx < self.len()`

**Comment by bombela** [comment]
Ohhhh. Nice one. If the element was last in the dense vec, then swap_remove has nothing to swap. I will add a regression test and the fix.

Thank you for this.

**Comment by EriKWDev** [comment]
Ran into this as well. Here are some tests that fail with old implementation but works with fix:

```rust
#[test]
fn remove2() {
    let mut s = SparseSet::with_capacity(200_000);
    let mut keys = Vec::new();

    for i in 1..=10_000 {
        keys.push(i);
        s.insert(i, 42);
    }

    for key in keys {
        s.remove(key);
    }
}

#[test]
fn remove3() {
    let mut s = SparseSet::with_capacity(100);
    s.insert(3, 42);
    s.insert(2, 42);
    s.insert(1, 42);

    s.remove(3);
    s.remove(2);
    s.remove(1);
}
```
