### ISSUE TITLE
Sparse set cannot hold an arbitrary value

### ISSUE THREAD

**Issue by ulex** [bombela/sparseset#4]
`dense` array is essential part of sparse set and cannot hold any arbitrary value. It must contain an value that verifies the index obtained from `sparce` array, because the index obtained from sparse array might be just garbage. Only in that case the `contains` method can be properly implemented.

This test indicates the problem:

```
#[test]
fn contains_reset() {
    let mut s = SparseSet::with_capacity(5);
    s.insert(1, ());

    s.clear();
    s.insert(5, ());
    assert!(s.contains(1) == false);
}
```

**Comment by bombela** [comment]
The key is stored inside the dense array and is compared. Not sure what is going on here, but that ain't good. I will investigate. Thank you for the bug report.

Side note, the test should fail on the insert(5) since it not lower than the capacity of 5 (0-indexing).

**Comment by ulex** [comment]
ah, sorry. I was confused by the declaration of  SparseSet
```
pub struct SparseSet<T> {
    dense: Vec<Entry<T>>,
    sparse: Vec<usize>,
}
```
I was thinking, that dense is just `Vec<T>`. This confused me and I wrote a test to understand how it works. And made a mistake in test. Thanks for very fast response!

By the way, why `dense` array is always defined with `with_capacity(size)`? In most scenarios such huge array isn't required and it would be nice to have an option in APIs to specify different capacity for dense.
